-- MySQL Script generated by MySQL Workbench
-- Fri Mar 18 10:55:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Base_Ejercicio3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Base_Ejercicio3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Base_Ejercicio3` DEFAULT CHARACTER SET utf8 ;
USE `Base_Ejercicio3` ;

-- -----------------------------------------------------
-- Table `Base_Ejercicio3`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Base_Ejercicio3`.`Usuario` (
  `NombreUsuario` VARCHAR(25) NOT NULL,
  `Clave` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`NombreUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
